/* config.h. Generated by cmake from config.h.cmake */

/* Indicates the byte order of your target system */
/* 1 if little-endian, 2 if big-endian. */
#define   SYSTEM_BYTEORDER 1

/* Defined if your compiler supports some byte swap functions */
/* #undef HAVE_GCC_BYTESWAP_16 */
/* #undef HAVE_GCC_BYTESWAP_32 */
/* #undef HAVE_GCC_BYTESWAP_64 */
/* #undef HAVE_GLIBC_BYTESWAP */
#define   HAVE_MSC_BYTESWAP 1
/* #undef HAVE_MAC_BYTESWAP */
/* #undef HAVE_OPENBSD_BYTESWAP */

/* Defined if your compiler supports codecvt */
#define   HAVE_STD_CODECVT 1

/* Defined if your compiler supports some atomic operations */
#define   HAVE_STD_ATOMIC 1
/* #undef HAVE_BOOST_ATOMIC */
/* #undef HAVE_GCC_ATOMIC */
/* #undef HAVE_MAC_ATOMIC */
/* #undef HAVE_WIN_ATOMIC */
/* #undef HAVE_IA64_ATOMIC */

/* Defined if your compiler supports some safer version of sprintf */
#define   HAVE_SNPRINTF 1
/* #undef HAVE_SPRINTF_S */

/* Defined if you have libz */
/* #undef HAVE_ZLIB */

/* Indicates whether debug messages are shown even in release mode */
/* #undef TRACE_IN_RELEASE */

#define TESTS_DIR "F:/Libs/taglib-master/tests/"
